### ISSUE TITLE
Common Lisp implementation logotypes

### ISSUE THREAD

**Issue by phoe** [azzamsa/lisp-logo#1]
I have made a collection of high-res logotypes (originally 4000x4000px) in Photoshop. The upside is that I still have the original PSD files, the downside is that they are pretty huge and the logos are raster rather than vector.
You can see the smaller transparent PNGs at https://imgur.com/a/QEd1p

**Comment by azzamsa** [comment]
I was really amazed, actually I want to make another logo other than the lizard, but my designer friend want to take a rest for while, I love JSCL logo that you made so I ask my friend to adapt that and change here and there.

fortunately you come up with so many beautiful logo, I often look for lisp logo but never find yours in that list, sometimes I find but it's just a thumbnail. 

why don't you put it in blog so people can easily find it :)

**Comment by phoe** [comment]
Is [this](https://blog.teknik.io/phoe/p/424) good enough?

**Comment by azzamsa** [comment]
Thank you so much Phone.
Thank you.  :)
